server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:mysql://52.35.177.255:3306/customerdb'
    username: 'root'
    password: 'mysqlmysql'
    driver-class-name: 'com.mysql.jdbc.Driver'
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://34.210.48.188:8761/eureka}
  instance:
    preferIpAddress: true
