server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:mysql://demodb:3306/demodb'
    username: 'root'
    password: 'mysql'
    driver-class-name: 'com.mysql.jdbc.Driver'
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry:8761/eureka}
  instance:
    preferIpAddress: true
