version: '2'

services:

  customerdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=customerdb
    ports:
      - "3306:3306"

  accountingdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=accountingdb
    ports:
      - "3305:3306"

  registry:
    image: senacortutorials/registry:stage-09
    ports:
      - "8761:8761"
    mem_limit: 1073741824

  config:
    image: senacortutorials/config:stage-09
    ports:
      - "8888:8888"
    mem_limit: 1073741824

  customer:
    image: senacortutorials/customer:stage-10
    ports:
      - "8081:8081"
      - "7081:7081"
    links:
        - customerdb
        - registry
        - config
    mem_limit: 1073741824

  accounting:
    image: senacortutorials/accounting:stage-10
    ports:
      - "8082:8082"
      - "7082:7082"
    links:
        - accountingdb
        - registry
        - config
    mem_limit: 1073741824

