version: '2'

services:

  customerdb:
    image: mysql
    container_name: customerdb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=customerdb
    ports:
      - "3306:3306"
    networks:
        - demonet

  accountingdb:
    image: mysql
    container_name: accountingdb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=accountingdb
    ports:
      - "3305:3306"
    networks:
        - demonet

  registry:
      image: senacortutorials/registry:stage-09
      container_name: registry
      ports:
        - "8761:8761"
      networks:
          - demonet

  config:
    image: senacortutorials/config:stage-09
    container_name: config
    ports:
      - "8888:8888"
    networks:
        - demonet

  customer:
    image: senacortutorials/customer:stage-09
    container_name: customer
    ports:
      - "8081:8081"
      - "7081:7081"
    depends_on:
        - customerdb
        - registry
        - config
    networks:
        - demonet
    
  accounting:
    image: senacortutorials/accounting:stage-09
    container_name: accounting
    ports:
      - "8082:8082"
      - "7082:7082"
    depends_on:
        - accountingdb
        - registry
        - config
        - customer
    networks:
        - demonet

networks:
  demonet:
  
