version: '2'

services:
  demodb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=demodb
    ports:
      - "3306:3306"

  accountingdb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=accountingdb
    ports:
      - "3305:3306"

  registry:
    image: senacortutorials/registry:local
    ports:
      - "8761:8761"

  config:
    image: senacortutorials/config:local
    ports:
      - "8888:8888"


  demo:
    image: senacortutorials/demo:local
    ports:
      - "8081:8081"
      - "7081:7081"
    links:
        - demodb
        - registry
        - config


  accounting:
    image: senacortutorials/accounting:local
    ports:
      - "8082:8082"
      - "7082:7082"
    links:
        - accountingdb
        - registry
        - config

