version: '2'

services:

  registry:
    image: senacortutorials/registry:stage-09
    ports:
      - "8761:8761"
    mem_limit: 1073741824

  config:
    image: senacortutorials/config:stage-09
    ports:
      - "8888:8888"
    mem_limit: 1073741824


  demo:
    image: senacortutorials/demo:stage-11
    ports:
      - "8081:8081"
      - "7081:7081"
    links:
        - demodb
        - registry
        - config
    mem_limit: 1073741824

  accounting:
    image: senacortutorials/accounting:stage-11
    ports:
      - "8082:8082"
      - "7082:7082"
    links:
        - accountingdb
        - registry
        - config
    mem_limit: 1073741824

